name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Hamster class has public constructor
      id: hamster-class-has-public-constructor
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Hamster class has public constructor
        setup-command: ''
        command: './gradlew test --tests "com.example.project.HamsterTest.testClassHasConstructor"  '
        timeout: 1
        max-score: 5
    - name: Hamster class has private string field name
      id: hamster-class-has-private-string-field-name
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Hamster class has private string field name
        setup-command: ''
        command: './gradlew test --tests "com.example.project.HamsterTest.testClassHasPrivateFieldName" '
        timeout: 1
        max-score: 5
    - name: Hamster has public getter for field name
      id: hamster-has-public-getter-for-field-name
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Hamster has public getter for field name
        setup-command: ''
        command: './gradlew test --tests "com.example.project.HamsterTest.testClassHasGetterName"   '
        timeout: 1
        max-score: 5
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        HAMSTER-CLASS-HAS-PUBLIC-CONSTRUCTOR_RESULTS: "${{steps.hamster-class-has-public-constructor.outputs.result}}"
        HAMSTER-CLASS-HAS-PRIVATE-STRING-FIELD-NAME_RESULTS: "${{steps.hamster-class-has-private-string-field-name.outputs.result}}"
        HAMSTER-HAS-PUBLIC-GETTER-FOR-FIELD-NAME_RESULTS: "${{steps.hamster-has-public-getter-for-field-name.outputs.result}}"
      with:
        runners: hamster-class-has-public-constructor,hamster-class-has-private-string-field-name,hamster-has-public-getter-for-field-name
